version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8090:80"
    volumes:
      - ./env/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/wp:/var/www/html
    depends_on:
      - db
      - php
  php:
    image: php:8.3
    build:
      context: env/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src/wp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

  wordpress:
    image: wordpress:6.5.3-php8.1
    volumes:
      - ./dist/wp/:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
      - php

volumes:
  db_data:
